### ISSUE TITLE
Roster loads before login is complete when using twofactor_totp app

### ISSUE THREAD

**Issue by rev138** [jsxc/jsxc.nextcloud#1] opened 2017-01-10 14:17 UTC
If the [TwoFactor_TOTP](https://github.com/nextcloud/twofactor_totp) app is enabled for 2FA, the chat roster window loads after the username/password are submitted, but before the TOTP code is entered. 

![screenshot from 2017-01-10 09-12-09](https://cloud.githubusercontent.com/assets/1538633/21809391/801e9a56-d715-11e6-8dfb-7a214df349a8.png)

**Comment by sualko** [comment] 2017-01-11 08:22
duplicate of jsxc/jsxc#436

**Closed by sualko** 2017-01-11 08:22 UTC
